- name: Install libselinux-python
  yum: name=libselinux-python
- name: Install shorewall core
  yum: name="http://www.shorewall.net/pub/shorewall/{{ shorewallmajorv }}/shorewall-{{ shorewallminorv }}/shorewall-core-{{ shorewallver }}.noarch.rpm" state=present
- name: Install shorewall main binary
  yum: name="http://www.shorewall.net/pub/shorewall/{{ shorewallmajorv }}/shorewall-{{ shorewallminorv }}/shorewall-{{ shorewallver }}.noarch.rpm" state=present
- name: Copy two interfaces skeleton
  shell: "/bin/cp /usr/share/doc/packages/shorewall-{{ shorewallminorv }}/Samples/two-interfaces/* /etc/shorewall/"
- name: Copy interfaces template
  template: src=interfaces.j2 dest=/etc/shorewall/interfaces
- name: Copy hosts template
  template: src=hosts.j2 dest=/etc/shorewall/hosts
- name: Copy zones, rules, policy and macros files
  copy: src=shorewall/web-servers/ dest=/etc/shorewall
- name: Copy shorewall configuration file to remote server
  copy: src=shorewall/config/shorewall.conf-back  dest=/etc/shorewall/shorewall.conf
- name: Create the /var/log/iptables file
  file: path=/var/log/iptables state=touch
- name: Stop iptables service
  service: name=iptables state=stopped
- name: Start shorewall service
  service: name=shorewall state=started
- name: Disable iptables service from starting on bootup
  shell: "/sbin/chkconfig iptables off"
- name: Disable ip6tables service from starting on bootup
  shell: "/sbin/chkconfig ip6tables off"
- name: Enable shorewall service to start on bootup
  shell: "/sbin/chkconfig shorewall on"
# - name: 'Finale rebooting the server'
#   command: "shutdown -r now"
